steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/reproduction-health', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/reproduction-health']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'reproduction-health', '--image', 'gcr.io/$PROJECT_ID/reproduction-health:latest', '--region', 'us-central1']

images: ['gcr.io/$PROJECT_ID/reproduction-health:latest']

options:
  logging: CLOUD_LOGGING_ONLY